### ISSUE TITLE
initial playlist directory

### ISSUE THREAD

**Issue by ttqf** [KenT2/tboplayer#119]
unless it's by design, there seems to be an issue with saving the location of the "initial playlist directory".
I haven't tracked how exactly works, but from what i could figure, when opening a csv list the "self.options.initial_playlist_dir" gets cleared and later saved in the "tboplayer.cfg" file.
my fix for this is:
`def _open_list(self, filename):`
`   #self.options.initial_playlist_dir = '' <-- comment this line`

**Comment by heniotierra** [comment]
That is more or less by design. Actually, It was a cheap fix for another problem. I'll see to it.
