### ISSUE TITLE
sound issue

### ISSUE THREAD

**Issue by hsynsysl** [KenT2/tboplayer#128]
everything is ok, but i can not get sound from aux 3.5mm connector of rpi-3

**Comment by hsynsysl** [comment]
I find the solution by option>edit
Thanks a lot the audio setting remained in hdmi mode

28 Şub 2018 13:59 tarihinde "heniotierra" <notifications@github.com> yazdı:

**Comment by heniotierra** [comment]
Ok. If you still have some problem related to this issue, you can reopen it.

**Comment by hsynsysl** [comment]
Ok, thank you

1 Mar 2018 07:55 tarihinde "heniotierra" <notifications@github.com> yazdı:
