### ISSUE TITLE
TBOplayer runs as root, but it does not run as a regular user.

### ISSUE THREAD

**Issue by seem-less** [KenT2/tboplayer#137]
Hello,

When I run TBOplayer as root it works fine. When I try to run with a regular user I get this error:

```
student@raspberrypi:/opt/tboplayer $ python tboplayer.py
Traceback (most recent call last):
  File "tboplayer.py", line 60, in <module>
    from ytdl import *
  File "/opt/tboplayer/ytdl.py", line 2, in <module>
    import pexpect
ImportError: No module named pexpect

```

pexpect is located in the following directory:

`/home/pi/.local/lib/python2.7/site-packages/pexpect`

the user "student" home directory is located here:

`/media/home/student/`

Any idea why the pexpect module can't be found?  Thanks

**Comment by heniotierra** [comment]
Hi,

Hum... Yes, your home user path is very likely the problem. I mean, when I wrote this code, I didn't expect the user the have a path different than /home/username/ ... 

I will see if I can fix this.

Thanks for your report,

**Comment by heniotierra** [comment]
UPDATED ANSWER ABOVE

**Comment by KenT2** [comment]
you can now do sudo apt-get install python-pexpect.

**Comment by heniotierra** [comment]
Good, that should be enough to fix the installer. :)

**Comment by heniotierra** [comment]
Fix must be fixed now.
