### ISSUE TITLE
set progress bar error problem

### ISSUE THREAD

**Issue by MichaelJWells** [KenT2/tboplayer#183]
I get the following message when I try to run a video in tboplayer: "**Error trying to set progress bar step**" and then omxplayer exits **without playing** the video.  

I have a new installation of Raspian Buster on a RPI 2 Rev B and I have followed all the manual install steps for the tboplayer which installed without error. I run the tboplayer from the command line with the following command: python3 /opt/tboplayer/  and when the window opens, I add a track and try to play it.  The error message appears in the background on the terminal CLI window I used to open the tboplayer.  [NB: I checked the debug box in the tboplayer options settings.]  

Testing shows that I am able to get the video to play normally with omxplayer from the command line. I also tested running the **sudo pkill -9 omxplayer** command in the command line as suggested in the installation page at github for tboplayer but this did not fix the error message.  I was able to run the video also using the omxplayerGUI application (for which I like less the GUI window layout generally in comparison to tboplayer).

I have read through the suggestions you gave to [mikcaren](https://github.com/KenT2/tboplayer/issues/180#issuecomment-633731496) about this issue before and despite having the debug option checked **I was unable to find a file named debug.log** in /opt/tboplayer/ or any of its sub-directories.

Of course I could go back to the old python2 version but I would like to ask if there are any suggestions about how to proceed to debug or fix this problem with the python3 version which would be most appreciated.

**Comment by heniotierra** [comment]
I don't have access to a Rapsberry Pi ATM, so I cannot fix this. My suggestion to try to circumvent it is making sure you're using python 3.7 or using the python 2 version. If you want to try to debug/fix it, I believe it might have something to do with the current time extraction in the method `_get_position` in lib/Omxplayer class. Maybe the position attribute is not being set correctly.

**Comment by MichaelJWells** [comment]
> I don't have access to a Raspberry Pi ATM, so I cannot fix this for now. My suggestion to try to circumvent this is making sure you're using python 3.7 or using the python 2 version.

$ python3 --version
Python 3.7.3
$ python --version
Python 2.7.16

I installed the tboplayer for python2 and the tboplayer is now working though I imagine with fewer bells and whistles than the python3 version of tboplayer.

Since you do not have access to a RPI, I assume that development on this project is mostly at a standstill?

> If you want to try to debug/fix it, I believe it might have something to do with the current time extraction in the method _get_position in lib/OMXPlayer class: maybe the position attribute is not being set correctly.

Unfortunately, I have only a rudimentary level of knowledge of python programming and feel that the debugging task should be left up to those with more knowledge than I at this point in time. 

> And, unfortunately, the debug option is not very useful right now.

After installing the python2 version of the tboplayer, I happened to notice a debug.log file in the /home/pi directory instead of the previously indicated /opt/tboplayer/ directory. I do not know if this log file is related to the tboplayer version 2 or 3.

Thank you for your advice.

**Comment by heniotierra** [comment]
> > I don't have access to a Raspberry Pi ATM, so I cannot fix this for now. My suggestion to try to circumvent this is making sure you're using python 3.7 or using the python 2 version.
> 
> $ python3 --version
> Python 3.7.3
> $ python --version
> Python 2.7.16
> 
> I installed the tboplayer for python2 and the tboplayer is now working though I imagine with fewer bells and whistles than the python3 version of tboplayer.
> 
> Since you do not have access to a RPI, I assume that development on this project is mostly at a standstill?
> 
> > If you want to try to debug/fix it, I believe it might have something to do with the current time extraction in the method _get_position in lib/OMXPlayer class: maybe the position attribute is not being set correctly.
> 
> Unfortunately, I have only a rudimentary level of knowledge of python programming and feel that the debugging task should be left up to those with more knowledge than I at this point in time.
> 
> > And, unfortunately, the debug option is not very useful right now.
> 
> After installing the python2 version of the tboplayer, I happened to notice a debug.log file in the /home/pi directory instead of the previously indicated /opt/tboplayer/ directory. I do not know if this log file is related to the tboplayer version 2 or 3.
> 
> Thank you for your advice.

I expected to have access to my RPi in the next week.
