### ISSUE TITLE
Full Screen bug?

### ISSUE THREAD

**Issue by DRAGxMEx2xHELL** [KenT2/tboplayer#188]
HI

Appears sometimes when i play a YouTube video through TBOPlayer it will go full screen by default unless i play the video again, then it will pop up as windowed. Sometimes in fullscreen my mouse & keyboard would become unresponsive where id have to pull the power from the wall as a buttons, and combinations would not respond. Not sure if this is a issue, or i overlooked something.

**Comment by heniotierra** [comment]
Hi,

Are you using the python 3 or pyhlthon 2 version?

Em Seg, 19 de out de 2020 14:02, DRAGxMEx2xHELL <notifications@github.com>
escreveu:

**Comment by DRAGxMEx2xHELL** [comment]
Sorry not sure, was using a raspberry pi 4 with TwisterOS 1.8.4

**Comment by heniotierra** [comment]
@DRAGxMEx2xHELL Which version date is in the "about" window? BTW, thank you for reposting this.

**Comment by DRAGxMEx2xHELL** [comment]
February 5th 2019 it appears

**Comment by heniotierra** [comment]
Ok, I'll try and reproduce this.

**Comment by DRAGxMEx2xHELL** [comment]
i ran into it 3 times over the course of like 2 hours.

**Comment by DRAGxMEx2xHELL** [comment]
upon looking into it, the unresponsive mouse and keyboard as on my end, but other than that, it going full screen upon first video, seems i need to repeatedly hit esc for it to exit, unless i missed something.

**Comment by heniotierra** [comment]
This only happens for streaming?

Em Qua, 21 de out de 2020 12:41, DRAGxMEx2xHELL <notifications@github.com>
escreveu:

**Comment by DRAGxMEx2xHELL** [comment]
Havent test anything else besides youtube streaming, sometimes get full screens where i cant exit, some i can, seems random. Is there any commands to exit full screen already in place?

**Comment by heniotierra** [comment]
I think the standard keyboard commands from omxplayer should work just
fine. To quit, hit q.

Em Qua, 21 de out de 2020 16:06, DRAGxMEx2xHELL <notifications@github.com>
escreveu:

**Comment by heniotierra** [comment]
@DRAGxMEx2xHELL Sorry, I misread you question. To exit full screen, hit F11. If that does not work, it probably means an issue with dbus. This kind of problem generally happens when there are 2 instances of omxplayer running at the same time. To force OMXPlayer to open in windowed mode, you can also try to set the optional arguments (OMXplayer options) in the config screen. For example: --win 1,1,500,400

**Comment by DRAGxMEx2xHELL** [comment]
Tried few things, and Q or F11 didnt let me exit full screen when it auto pops up at times.

**Comment by heniotierra** [comment]
Ok, this PR fixes it: https://github.com/KenT2/tboplayer/pull/189
If you have any other problem, please, reach out! 
And thank you again, @DRAGxMEx2xHELL . :)
