### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Botspot** [KenT2/tboplayer#190]
Someone just opened an issue on Pi-Apps reporting that TBOPlayer is not working.

See: https://github.com/Botspot/pi-apps/issues/111
Below I've copied the first post from there:
> I was trying a lot and it seems to be a problem from the script:
> Only a missing "," before the "}". Expected: ",}"
> ![2020-11-27-222315_800x480_scrot](https://user-images.githubusercontent.com/31230743/100492428-4909b280-3102-11eb-86a1-bfee2b2f6614.png)
> 
> **I've fixed it but then it got me this next:**
> ![2020-11-27-223438_800x480_scrot](https://user-images.githubusercontent.com/31230743/100492445-69397180-3102-11eb-8747-bb4277355304.png)

**Comment by fabianmendes** [comment]
Hi, guys. You can now close this issue! Thanks
