### ISSUE TITLE
Could you make omxplayer output to the selected ALSA output device?

### ISSUE THREAD

**Issue by Botspot** [KenT2/tboplayer#193]
Title says it all. I'd like if omxplayer obeyed my ALSA setup and outputted to the right audio device.

**Comment by heniotierra** [comment]
I guess I can try. ;)

**Comment by heniotierra** [comment]
@Botspot When do you suggest we do this? Upon a media playback? I'm thinking of doing that configuration upon first execution.

**Comment by Botspot** [comment]
> @Botspot When do you suggest we do this? Upon starting a media playback? I'm thinking of doing that configuration upon first execution of tboplayer. We cannot change the output port while a media is being played.

What ever option is easiest I suppose. Doesn't omxplayer have a built-in ALSA output device flag?

**Comment by heniotierra** [comment]
Yeah, I know, and tboplayer offers an ALSA output option. I not sure I
understand your request. My ideia is getting the current output port for
audio in the OS and using that for automatically setting OmxPlayer output.
I may have misunderstood your requst as I have very little knowlegde of
working with ALSA.

Em Dom, 6 de dez de 2020 18:03, Botspot <notifications@github.com> escreveu:

**Comment by Botspot** [comment]
Basically, here's what happened:

- I have the Pi's analog output selected as the default audio output via ALSA.
- But TBOPlayer appears to ignore that output - it's always sent sound through my HDMI screen.

So I thought it might be a good idea if you were to change that, and make tboplayer obey the ALSA standard.

**Comment by Botspot** [comment]
Okay sure enough, there's a setting for it. And it works fine.
![2020-12-06-153412_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/101292999-8e9c3e80-37d8-11eb-9ca7-7a72b06f83ca.png)

So now I'm wondering: Why isn't ALSA output the default on a fresh tboplayer installation? (to me it seems like using alsa's selected output device would prove to satisfy most users better)

**Comment by heniotierra** [comment]
> to me it seems like using alsa's selected output device would prove to satisfy most users bette0r

Maybe your're right. I've always used HDMI output.

**Comment by heniotierra** [comment]
Done, it's in the master branch
