### ISSUE TITLE
Paste click/touch feature for URLs

### ISSUE THREAD

**Issue by fabianmendes** [KenT2/tboplayer#194]
Hi, excuse me. Is that possible that you make it available to Paste links by right-clicking? I always have to CTRL+V shortcut for that, I can't do it only using my mouse or neither my touchscreen by long-press.

Thank you!

**Comment by heniotierra** [comment]
Hey! Yes, it is!

**Comment by heniotierra** [comment]
Done, it's in the master branch

**Comment by fabianmendes** [comment]
Amazing!
