### ISSUE TITLE
GPIO buttons?

### ISSUE THREAD

**Issue by varobw** [KenT2/tboplayer#198]
Hi! Im looking to using this as a media player with an ATEM Mini pro. Im not well versed in linux, so im not really sure what the DBUS is. Does that mean i can wire a few buttons and control pause, stop, next, etc? How would i do that?

Thanks and excuse my english!

**Comment by heniotierra** [comment]
Hi @varobw !
Yes, you can do just that! [This post](https://github.com/KenT2/tboplayer/issues/92#issuecomment-294323303) explains how you can do it. If you need further help, please reach out, or reopen this thread!
