### ISSUE TITLE
Open list doesn't download URLs

### ISSUE THREAD

**Issue by fabianmendes** [KenT2/tboplayer#199]
hi, excuse me. after opening a saved CSV list or playlist.. the app doesn't load them.

**Comment by fabianmendes** [comment]
Ok, I've just seen that it only happens when the list of videos was added as Playlist. The issue is related to Adding Tracks without their respective individual URLs. I'll create a new issue.
![2021-05-05-155605_800x480_scrot](https://user-images.githubusercontent.com/31230743/117220934-42c8e200-add6-11eb-9f8b-93215fd7fe96.png)

**Comment by heniotierra** [comment]
Hi Fabian.  You may find out that the sabe playlist fraturei is not very
useful for youtube videos cause the URLs saved are actually temporary. If
you try to access it some time later, It will fial tô load.

Em qua, 5 de mai de 2021 20:16, V. Fabian T. Mendes C. <
***@***.***> escreveu:

**Comment by fabianmendes** [comment]
Hi @heniotierra thanks for the reply ! All right, thanks to know. I'll update #200 issue soon (I sadly wonder that) so I was thinking if we can add on the code something that could read videos ' URLs from playlist URL via **scrapping**. I'll try it out; the thing is that you use Python2.7 and I am not very well familiarized with it!

**Comment by heniotierra** [comment]
No need for scrapping, that's unnecessary work. For this to work, we should just keep the original URL - which we discard as of now - in memory, and upon saving the playlist, use that instead of the downloaded URL. Then, when loading the playlist, use the ytdl object to fetch the media URLs.

**Comment by fabianmendes** [comment]
Ooh I get it, Instead of Saving a list of Tracks, we save the Playlistlist instead, right? but, How can we let know TBOPlayer python code when saving only the playlist URL and not tracks (because it will save tracks without HTTP URL on it)/
