### ISSUE TITLE
licence.md is Pi Presents' licence

### ISSUE THREAD

**Issue by heniotierra** [KenT2/tboplayer#27]
Don't know if this is really a problem, but licence.md is Pi Presents'

**Comment by popiazaza** [comment]
not sure what you mean, but I don't think licence.md have any problem since .md file is just a typical text file.

**Comment by heniotierra** [comment]
@popiazaza Sure, what I mean is, it's a licence for another program.

**Comment by popiazaza** [comment]
oh i see, he just copy & paste from Pi Presents.

**Comment by KenT2** [comment]
Whoops, licence corrected
