### ISSUE TITLE
Installing TBOPlayer on Raspbian

### ISSUE THREAD

**Issue by uksa** [KenT2/tboplayer#40]
I had a few issues with installing the TBOPlayer, this was on a fresh install however without the following it won't work:

1. sudo apt-get install python-pip
2. pip install pexpect
3. pip install ptyprocess
4. apt-get install python-gobject-2

Information could be helpful to others installing.

Linux 4.0.7+

**Comment by heniotierra** [comment]
Thanks for the input. :) 

I had not tested it on a fresh Raspbian install. 
The installer should install pexpect, but maybe there's some some catch related to ptyptocess.
gobject was recently added as a requirement for DBus connectivity, but I thoguht it would be pre-installed.

That will be fixed soon. I'll send the patch along with a new feature for TBOPlayer.

**Comment by uksa** [comment]
I'm sure pexpect was fine, however I think this was the full list. I've also tested in a 3.5" screen and it seems to be working ok so :)

Close the issue when ever you like...

**Comment by heniotierra** [comment]
This should be fixed by https://github.com/KenT2/tboplayer/pull/41 now.

**Comment by somesmart** [comment]
I just installed this on Raspbian and had to manually install pexpect and python-magic in order to get it to work. Let me know if you need more information!

**Comment by heniotierra** [comment]
Weird. Which version of Raspbian did you install? Thank you.

**Comment by somesmart** [comment]
I've had it for a while so I'm still on Rasbian 7 (wheezy)

**Comment by heniotierra** [comment]
What these two packages have in common is that thay both are installed with pip. So my guess is that your problem is related to pip. Did you have to install pip too? Did you use pip normally to install the packages?

**Comment by somesmart** [comment]
No, pip was already installed. I was just ran the scripts from the manual installation instructions:

`pip install --user pexpect ptyprocess python-magic`
