### ISSUE TITLE
[Raspberry Pi 3] Videos appear displaced?

### ISSUE THREAD

**Issue by heniotierra** [KenT2/tboplayer#48]
Seems like videos are shown displaced by ~50px in both axes(x,y), in the Raspberry Pi 3 (running Raspbian Jessie). I just noticed this, and ATM I have no idea of what might be the cause. Some investigation is required.

It would be great if someone could test if this also happens in Raspbian Jessie with the Raspberry Pi 1 (or 2).

**Comment by heniotierra** [comment]
It would be welcome if someone could test if this also happens in Raspbian Jessie with the Raspberry Pi 1.

**Comment by KenT2** [comment]
Sounds like overscan problems. Run PP with the -d command line option.It will print out the screen size that it has obtained from Raspbian.

**Comment by heniotierra** [comment]
Hi Ken, the player now uses the functions ```screen_width``` and ```screen_height``` to get the screen resolution, which, yes, is used to place the video in the right place. I guess I must have made a mistake somewhere.

**Comment by KenT2** [comment]
Whoops, I answered the question thinking it was a Pi Presents issue. My suggestion of overscan not being set correctly by the OP is still relevant. It  would make the result of your correct corrections incorrect.

**Comment by heniotierra** [comment]
Then, please, enlighten me, sir! I do not know what overscan is nor how that affects TBOplayer. May HDMI cause that kind of problem?

**Comment by koeshi** [comment]
You can disable Overscan by following Menu>Preferences>Raspberry Pi Configuration and then setting Overscan to Disabled.

**Comment by heniotierra** [comment]
Oooh! That's it! It worked like a charm! Thank you @koeshi !

**Comment by heniotierra** [comment]
I'm gonna add this to the Troubleshooting section of the README.md file.
