### ISSUE TITLE
Put the player inside /opt instead /home/pi/tboplayer

### ISSUE THREAD

**Issue by NSasquatch** [KenT2/tboplayer#53]
I just noticed that you install your player inside the `/home/pi/tboplayer` directory. I think `/opt` would be better suited. First, [it exists specifically for applications like yours](http://askubuntu.com/questions/6897/where-to-install-programs), and second - there is no danger of it getting deleted.

**Comment by heniotierra** [comment]
Ok, It will be done! Thank you! :)

**Comment by heniotierra** [comment]
Done! Thank you again @NSasquatch.
