### ISSUE TITLE
python-tk missing

### ISSUE THREAD

**Issue by detrax** [KenT2/tboplayer#58]
During the installation with your script, python-tk seems not to be considered to install, if missing.

**Comment by heniotierra** [comment]
Hi,

Just type:
sudo apt-get install python-tk

Em 08/11/2016 05:04, "detrax" <notifications@github.com> escreveu:

**Comment by heniotierra** [comment]
I guess you've received an error message when trying to launch tboplayer...

Em 08/11/2016 10:25, "Hênio Tierra" <heniotster@gmail.com> escreveu:

**Comment by heniotierra** [comment]
Added python-tk to installation setup and manual instructions. TY.
