### ISSUE TITLE
Not playing audio when linked to application

### ISSUE THREAD

**Issue by Titowam** [KenT2/tboplayer#6]
So think of it like this:
You have a text document that you want to read, so you double click it and it opens some sort of word prcessor and the file loads.

Thats what I want, so I made a command that loads up the GUI and opens the file, like this:
/usr/bin/python /home/pi/bin/tboplayer.py "%f"
The problem is that it doesnt do the %f part, it only loads up the GUI.

Is there a way to make this work, and perhaps also drag-and-drop?

**Comment by KenT2** [comment]
I believe you could do this by modifying the TBOplayer code to read the file name from the command line and play the file but I don't know how. Would also mean some sort of assignment to the filetype. Not so sure about drag and drop, is it supported by LXDE desktop?

**Comment by heniotierra** [comment]
I guess this is possible now. :)
