### ISSUE TITLE
White text on white background

### ISSUE THREAD

**Issue by ChrisSaldivar** [KenT2/tboplayer#60]
When adding tracks all of the text is white and I can't see them. I have to click where the tracks are for them to turn black. This is on raspberry pi 3 running Ubuntu mate.

**Comment by heniotierra** [comment]
That can be fixed. Will do soon. Thanks.

**Comment by heniotierra** [comment]
@ChrisSaldivar This should have been fixed. Can you try it? It's in the main branch.
