### ISSUE TITLE
Issue with sound

### ISSUE THREAD

**Issue by rockman55** [KenT2/tboplayer#7]
I have a usb sound thumb drive and I can play sounds on it with the terminal oxyplayer, but I only get sound through my hdmi with your GUI app. Tried to change settings to HDMI and plug in the external speaker from the monitor (still get sounds from the built in speakers) also tried AUTO and Local with no success, Would like to get the sound playing through my USB sound card.

Thanks

**Comment by KenT2** [comment]
Interesting, I was under the impression that USB audio couldn't be used with omxplayer, obviously I was wrong. What command line option do you use to get omxplayer to work with usb, I would be interested to know.
Whatever it is set the audio option in TBOPlayer to auto and in the omxplayer options field place the command lin option you use with the preceeding - or -- add a space before and after the string to be sure it works
