### ISSUE TITLE
mp3 track skips to end on playback

### ISSUE THREAD

**Issue by deembe** [KenT2/tboplayer#70]
Hi, I've just done a fresh install of Raspian, Omxplayer and tboplayer.  

Playback of an mp3 file in tboplayer skips to the end of the track. 
The same mp3 plays fine manually in omxplayer -o local {filename} usage. 
Youtube video plays OK via HDMI.

tboplayer is 17 Jan 2017 build
omxplayer is 23 Sept 2016 build.

**Comment by heniotierra** [comment]
Hum... yes... I think I know what's happening. Will have a look at this. Thanks!

**Comment by heniotierra** [comment]
There, it's fixed!

**Comment by deembe** [comment]
Many thanks, that's working and I'm listening to Chasing Cars by Snow Patrol.... 👍
