### ISSUE TITLE
usb DVB-t tuner 

### ISSUE THREAD

**Issue by pejko** [KenT2/tboplayer#84]
Hi this is not and issue more like a question. Is it possible to load/play tv chanels usinf tboplayer and an usb dvbt tunner? i managed to find the drivers for tunner and test it with vlc so drivers are fine, just need to know how to hook it together with tboplayer.
Ty for your time and this great GUI :)

**Comment by heniotierra** [comment]
Hi @pejko , I believe you should be able to either open the device (inside /dev) directly as a normal track, or you could get a url which then you'd paste into tboplayer's url dialog. If omxplayer can play it, then tboplayer must be capable of that too. Or did you try those things already without success?

**Comment by pejko** [comment]
wow thank you for such fast reply , unfortunately i have to reinstall raspbian  :D but will write back asap .

**Comment by heniotierra** [comment]
I guess you've had your problem solved, so I'll close this issue. If you need more help, you can reopen it.
